### PR TITLE
Update StateUpdateOutput & Add PendingStateUpdate 

### LINKED ISSUE #228: Splitting of STATE_UPDATE
State update was split into:
- STATE_UPDATE
- PENDING_STATE_UPDATE

Need modification:
- `StateUpdateOutput` in `rpcv02/types.go`
- `StateUpdate` method

### LINKED ISSUE #229: Modify `StateDiff` struct properties
StateDiff struct: 
- [ ] Add `replaced_classes` properties
- [ ] Replace DeclaredContractHashes by deprecated_declared_classes and declared_classes

### PR DESCRIPTION
**Pull request by mattcoburn24**
Updated StateDiff for new PendingStateUpdate type. closes #229 
Used new PendingStateUpdate to split StateUpdateOutput, closes #228 
update mock_test.go and block_test.go

### CODE REVIEW

**Comment by coburn24** [comment]
closes #228 #234

**Comment by rianhughes** [comment]
Hey nice work so far. It looks like you need to update block_test.go and mock_test.go. The PR shouldn't break rpc tests on mock or devent.

**Comment by mattcoburn24** [comment]
@rianhughes Fixed mock_test.go  & block_test.go

mock_test.go changes
1. mock_starknet_getStateUpdate 
StateUpdateOutput updated
2. mock_starknet_getEvents
EventOutput updated

Fixed block_test.go changes
1. updated TestStateUpdate to support PendingStateUpdate

**Comment by rianhughes** [comment]
The pending state updates look good

However, since you updated the events types, starknet_events no longer returns the correct type. Would you mind updating starknet_events (inc the mock function, and make sure it passes on mock and devnet, etc)?

**Comment by cicr99** [comment]
Could you also address this pr onto `main` branch instead of `rpcv03`?

**Comment by mattcoburn24** [comment]
@rianhughes just rebased with master, removed the link for #234 and changed the name of the PR as not to include Event changes, can we merge it as is and go from there or do you want me to remove the updates i made to types_event.go?
@cicr99 changed to main

**Review by rianhughes — APPROVED** [review]

**Pull request merged**
