### PR TITLE
Refactor to use use unwrapErr() throughout the codebase

### PR DESCRIPTION
**Pull request by Bitcoinnoobie**
with related to issue #318

### CODE REVIEW

**Comment by stranger80** [comment]
@Bitcoinnoobie I took liberty to rename this PR for readability

**Review by rianhughes — APPROVED** [review]

**Comment by rianhughes** [comment]
This [issue](https://github.com/NethermindEth/starknet.go/issues/361) should be resolved before this PR is merged. We should run tests on PRs

**Comment by cicr99** [comment]
There are a few places (other that the ones that were addressed) where no `switch` statement is used but it would be good to handle the errors using `tryUnwrapToRPCErr` method as well:
- [BlockHashAndNumber](https://github.com/NethermindEth/starknet.go/blob/8906950018b4a6d76fcaecc8499c76ad6f679d99/rpc/block.go#L2)
-  [BlockWithTxHashes](https://github.com/NethermindEth/starknet.go/blob/8906950018b4a6d76fcaecc8499c76ad6f679d99/rpc/block.go#L56) 
- [StateUpdate](https://github.com/NethermindEth/starknet.go/blob/8906950018b4a6d76fcaecc8499c76ad6f679d99/rpc/block.go#L79)
- [BlockWithTxs](https://github.com/NethermindEth/starknet.go/blob/8906950018b4a6d76fcaecc8499c76ad6f679d99/rpc/block.go#L103)
- [TransactionByHash](https://github.com/NethermindEth/starknet.go/blob/8906950018b4a6d76fcaecc8499c76ad6f679d99/rpc/transaction.go#L66)
- [TransactionReceipt](https://github.com/NethermindEth/starknet.go/blob/8906950018b4a6d76fcaecc8499c76ad6f679d99/rpc/transaction.go#L103)

Could these be modified too?

**Comment by cicr99** [comment]
> This [issue](https://github.com/NethermindEth/starknet.go/issues/361) should be resolved before this PR is merged. We should run tests on PRs

Also, this was already merged in, but in order to be applied to this PR I think it's necessary to fetch the latest changes from main into this branch

**Review by cicr99 — APPROVED** [review]

**Pull request merged**
