### PR TITLE
Bind RPC Responses to Errors

### PR DESCRIPTION
**Pull request by mattcoburn24**
hey @rianhughes 👋🏼
Just wanted to check with you first that I was formatting the error correctly using the RPCError type before continuing.

### CODE REVIEW

**Comment by rianhughes** [comment]
Hey, good idea! 

Have a look at [BlockWithTxHashes](https://github.com/NethermindEth/starknet.go/blob/main/rpcv02/block.go#L50). Also, try to use the error variables in errors.go (they should all be there)

**Review by rianhughes — CHANGES_REQUESTED** [review]
Nice work! You just need to merge main, and squash the PR.

**Comment by mattcoburn24** [comment]
@rianhughes @cicr99 
pulled from upstream, Squashed and merge main into my BindRPCResponsesToErrors branch, got a conflict
and used deleted file from main. Let me know if its ok. 
Screen Shot 2023-07-31 at 3 37 38 PM
PR #263 was a result of me first merging BindRPCResponseToErrors into my remote main and creating a PR from from my main branch but meant to keep it with this PR #

**Comment by rianhughes** [comment]
You shouldn't delete events.go, not sure what's going wrong. It looks like your branch is currently 6 commits behind main, so it might be worth trying the following: 1) update your the main branch on your fork, 2) merge main into BindRPCResponsesToErrors.
Hopefully this doesn't give any conflicts. Then if that looks good, try squashing.

**Pull request closed without merging**
