### PR TITLE
Code documentation

### PR DESCRIPTION
**Pull request by aquental**
Code documentation for all files.
First phase: GoDoc comments on 61 files.

### CODE REVIEW

**Comment by stranger80** [comment]
I feel this should wait until package refactoring is committed, then merged back to "doc-enriched" branch.

**Comment by stranger80** [comment]
Will resolve #303

**Comment by rianhughes** [comment]
Very nice work! 

Do you think we could standardise the comment format? For example, the documentation format for utils.go/PrivateToPoint is quite nice: 
 1) Name of function and what it does, 
 2) explain the logic if needed (optional?), 
 3) Parameters, 
 4) Returns. 
Imo this is nicer to work with than the documentation format for rpc/chain.go/Syncing

**Comment by stranger80** [comment]
@aquental I think it is now required to merge the current state of main branch to your working branch - as the structure has changed significantly.

**Pull request closed without merging**
